### ISSUE TITLE
Unable to post on the queue

### ISSUE THREAD

**Issue by gspavansai** [logstash-plugins/logstash-output-sqs#17]
Unable to access SQS queue '': The specified queue does not exist for this wsdl version. {:level=>:error}

I'm currently running logstash 2.4. I tried even by replacing aws-java-sdk-1.11.21.jar. I did not work. When we did our initial evaluation with 2.2 it was working and that is why we chose this approach.

 sqs {
                       queue => "queuename"
                       region  => "us-east-1"
                       access_key_id => "key"
                       secret_access_key => "secret"
                }

I'm currently blocked with my implementation.

There is no connectivity issue. Using awscli I'm able to publish the queue.

console error says 
Failed to flush outgoing items {:outgoing_count=>10, :exception=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-sqs-2.0.4/lib/logstash/outputs/sqs.rb:129:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in`buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in`buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-sqs-2.0.4/lib/logstash/outputs/sqs.rb:121:in`receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/output_delegator.rb:130:in`worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:293:in`output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:293:in`output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:224:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:193:in`start_workers'"], :level=>:warn}

We have complete access to queue in AWS
"Action": [
                "sqs:SendMessage",
                "sqs:SendMessageBatch"
            ]

**Comment by kori0129** [comment]
Same problem here. Can someone look into this please?

**Comment by joshuaspence** [comment]
I think that you need to add permissions for `sqs:GetQueueUrl`.

**Comment by jrgns** [comment]
@gspavansai Can you confirm if adding permissions for `sqs:GetQueueUrl` fixes the problem?

Also, @joshuaspence pretty much rewrote the plugin, and it's been released. Maybe give it a try?
