### ISSUE TITLE
logstash.outputs.sqs Failed to flush outgoing items 

### ISSUE THREAD

**Issue by qhh0205** [logstash-plugins/logstash-output-sqs#22]
**Hello everyone, i use sqs as logstash output. But logstash start after a while on the error, the error message is as follows:**
[2017-02-21T21:50:28,548][WARN ][logstash.outputs.sqs     ] Failed to flush outgoing items {:outgoing_count=>10, :exception=>"AWS::SQS::Errors::BatchRequestTooLong", :backtrace=>["/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in `return_or_raise'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'", "(eval):3:in `send_message_batch'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/sqs/queue.rb:551:in `batch_send'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/logstash-output-sqs-3.0.2/lib/logstash/outputs/sqs.rb:129:in `flush'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/home/ec2-user/logstash/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/logstash-output-sqs-3.0.2/lib/logstash/outputs/sqs.rb:121:in `receive'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:297:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:296:in `output_batch'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/home/ec2-user/logstash/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}

- Logstash Version:logstash-5.0.0
- Operating System:Centos Linux
- Plugin Version: logstash-output-sqs-3.0.2
- Config File :
output{
    if [type] == "crm_app_access_log" {
        sqs {
            queue => "crm_app_access_log"
            access_key_id => “xxxxxxxxxxxxxxxxxx”
            secret_access_key => "xxxxxxxxxxxxxxxxxx"
            region => "ap-northeast-1"
        }
    }

    if [type] == "crm_web_access_log" {
        sqs {
            queue => "crm_web_access_log"
            access_key_id => "xxxxxxxxxxxxxxxxxx"
            secret_access_key => "xxxxxxxxxxxxxxxxxx"
            region => "ap-northeast-1"
        }
    }

    if [type] == "nginx_access_log" {
        sqs {
            queue => "nginx_access_log"
            access_key_id => "xxxxxxxxxxxxxxxxxx"
            secret_access_key => "xxxxxxxxxxxxxxxxxx"
            region => "ap-northeast-1"
        }
    }
}

I checked a lot of information did not solve, do not know where the problem lies, cay anyone tell me what's the reason? thanks.

**Comment by joshuaspence** [comment]
This issue should have been fixed in version 4.0.0

**Comment by joshuaspence** [comment]
Specifically, see #20.
